version: "3.8"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks:
      - intranet

  frontend:
    build: .
    container_name: covid_kids
    restart: always
    ports:
      - "80:80"
    networks:
      - intranet

networks:
  intranet:

volumes:
  portainerdata:
    